### PR TITLE
Refactor bridger 

### LINKED ISSUE #196: Docs: the darwinia node bridger connect require flag `--enable-offchain-indexing 1`

### PR DESCRIPTION
**Pull request by fewensa**
Related:
- [Refactor and design merging between bridger and s2s bridge relay?](https://github.com/darwinia-network/bridger/issues/177)
- [BridgeTask Trait Draft](https://github.com/darwinia-network/bridger/issues/186)
- [Better services management ](https://github.com/darwinia-network/bridger/issues/103)

With: 
- ~~https://github.com/darwinia-network/substrate-api-client/pull/1~~
- https://github.com/darwinia-network/substrate-api-client/pull/3
- https://github.com/darwinia-network/substrate-api-client/pull/2

Work:

- [x] ~~bridge shared~~
      discard shared https://github.com/darwinia-network/bridger/pull/190/commits/8e109617287f961ee821b63bb19b96d3b43ca33f
- [x] darwinia-ethereum bridge https://github.com/darwinia-network/bridger/pull/195
- [x] substrate to substrate bridge (pangolin-millau) https://github.com/darwinia-network/bridger/pull/194
- [x] Fixed #196 

---

- [x] use `~/.bridger/` default `base-path` for bridger. https://github.com/darwinia-network/bridger/pull/190/commits/7dd1032c74756370237be5f57aa266719d318f8e
- [ ] update ci release.yml https://github.com/darwinia-network/bridger/pull/202
- [ ] update Dockerfile https://github.com/darwinia-network/bridger/pull/202
- [ ] update README.md https://github.com/darwinia-network/bridger/pull/202
- [ ] darwinia-ethereum command https://github.com/darwinia-network/bridger/pull/203
- [x] fix code check https://github.com/darwinia-network/bridger/pull/190/commits/0f14bf3b6ba5c43b19ed35446f36a4ebed57dae2 https://github.com/darwinia-network/bridger/pull/190/commits/84470f629c13048467f77f41a6bc0866206bfbda https://github.com/darwinia-network/bridger/pull/190/commits/53340e2f36475465ac60ff3cb295ebee76f425cf https://github.com/darwinia-network/bridger/pull/190/commits/2179985588b237c2d5cf49dfceed32adce0febd1
- [x] adjust the directory https://github.com/darwinia-network/bridger/pull/201 https://github.com/darwinia-network/bridger/pull/190/commits/8906808cffc12102c702a25a9a1faf9674ef963a

---
Needs to be resolved, but not now 
- [ ] https://github.com/darwinia-network/bridger/issues/199 https://github.com/paritytech/parity-bridges-common/issues/1055
- [ ] kv command support complex data types

### CODE REVIEW

**Comment by HackFisher** [comment]
Some suggestions but does not have to be done in this PR:

- [ ] Better Naming
- [ ] Auto generated cli using json rpc, similar to geth, eliminate the effort to write the cli codes.
- [ ] How to generate default template config for specific task, for easy getting started with config settings?
- [ ] Should we use a global kv db instead of kv db components managed by different tasks, api simplicity vs flexibility. After rethinking, I'm not sure how to tradeoff the design here for now, we can postpone this suggestion if you are not sure with it too.
- [ ] How to send message from cli/http request to services, and how to query/set key value to db from cli. (Migrating existing feature commands).

**Comment by fewensa** [comment]
>     * Should we use a global kv db instead of kv db components managed by different tasks, api simplicity vs flexibility. After rethinking, I'm not sure how to tradeoff the design here for now, we can postpone this suggestion if you are not sure with it too.

I think, the kv db create by bridge and use `lifeline::Resource` share to task, any task want use it, just take it from bus resource. it's like bridge-shared. the bridge maintains a global state. of course, this requires the task to choose whether to need this state by itself .

The implement like this

https://github.com/darwinia-network/bridger/blob/53636c22976cfe7424284cdc66419028b98522d8/bridger/bridge-task/task-darwinia-ethereum/src/task.rs#L37

https://github.com/darwinia-network/bridger/blob/53636c22976cfe7424284cdc66419028b98522d8/bridger/bridge-task/task-darwinia-ethereum/src/bus.rs#L7

**Comment by HackFisher** [comment]
@fewensa CI(Lint) failed

**Comment by HackFisher** [comment]
Since task-pangolin-millau is merged, can we remove provider/substrate-relay, and move&update docs/substrate-relay to task-pangoin-millau/docs

**Comment by fewensa** [comment]
> 
> 
> Since task-pangolin-millau is merged, can we remove provider/substrate-relay, and move&update docs/substrate-relay to task-pangoin-millau/docs ?

Yes. I'll do that

**Comment by fewensa** [comment]
Related: https://github.com/paritytech/parity-bridges-common/issues/1055

**Comment by fewensa** [comment]
@wuminzhe  some test error in evm-log-tracker crate

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
