### PR TITLE
fix return type bug

### PR DESCRIPTION
**Pull request by xiaoch05**
if the return value is an Option type, we must define it in macro

### CODE REVIEW

**Review by HackFisher — APPROVED** [review]
@fewensa @wuminzhe Please review.

**Comment by wuminzhe** [comment]
Is there any difference?

**Comment by xiaoch05** [comment]
> Is there any difference?

yes, if we rename the type. subxt will not recognize it as an Option type. then it calls fetch_default. And at last it decode the value by the Option type. So the result becomes None.

**Comment by wuminzhe** [comment]
> > Is there any difference?
> 
> yes, if we rename the type. subxt will not recognize it as an Option type. then it calls fetch_default. And at last it decode the value by the Option type. So the result becomes None.

got it

**Comment by HackFisher** [comment]
I think it does have differences to macro.

**Review by wuminzhe — APPROVED** [review]

**Comment by HackFisher** [comment]
substrate-subxt's这个特殊处理的设计有点坑。

**Comment by xiaoch05** [comment]
> > Is there any difference?
> 
> yes, if we rename the type. subxt will not recognize it as an Option type. then it calls fetch_default. And at last it decode the value by the Option type. So the result becomes None.

the two different results.
```
{ ident: Ident { ident: "MmrRootsToSignReturn", span: #0 bytes(34899..34919) }, arguments: AngleBracketed(AngleBracketedGenericArguments { colon2_token: None, lt_token: Lt, args: [Ty
pe(Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "T", span: #0 bytes(34920..34921) }, arguments: None }] } }))], gt_token: Gt }) }
```

```
{ ident: Ident { ident: "Option", span: #0 bytes(34887..34893) }, arguments: AngleBracketed(AngleBracketedGenericArguments { colon2_token: None, lt_token: Lt, args: [Type(Path(TypePa
th { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "MmrRootsToSignReturn", span: #0 bytes(34894..34914) }, arguments: AngleBracketed(AngleBracketedGenericAr
guments { colon2_token: None, lt_token: Lt, args: [Type(Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "T", span: #0 bytes(34915..34916) }, a
rguments: None }] } }))], gt_token: Gt }) }] } }))], gt_token: Gt }) }
```

**Pull request merged**
