### PR TITLE
Query `spec_version` and `transaction_version` from chain

### PR DESCRIPTION
**Pull request by fewensa**
Related:
- https://github.com/paritytech/parity-bridges-common/pull/1248/
- https://github.com/darwinia-network/parity-bridges-common/pull/11
- https://github.com/darwinia-network/darwinia/issues/814

Closes https://github.com/darwinia-network/bridger/issues/347

### CODE REVIEW

**Comment by fewensa** [comment]
```
[2021-12-13T07:21:08Z DEBUG task_pangolin_pangoro::service::init] source client -> Client { genesis_hash: 0x8e256132e4d6412325b1485dee50c5d2a19a485095b4118b9b555be873c8c7d8 }
[2021-12-13T07:21:08Z DEBUG task_pangolin_pangoro::service::init] target client -> Client { genesis_hash: 0x1a20ef2847058288242829bcd53b0cb228e445e95e195d06758fc23e42625e5d }
[2021-12-13T07:21:11Z INFO  substrate_relay_helper::headers_initialize] Prepared initialization data for Pangolin-headers bridge at Pangoro: InitializationData { header: Header { parent_hash: 0xd8d7323e316ce0f25e2b142f9c90566f58ea629a3ba846356562e7b04626dd4c, number: 35, state_root: 0x233b762a4ae4fe637e393fe7ab698b9def9f7148cd4fc65c84cecc9d264fc162, extrinsics_root: 0x17bf5d50ec39b312a36fbe8f9fd1e4b2d79126af4bceba2a59436827f36824e4, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [1, 0, 0, 0, 0, 185, 40, 73, 16, 0, 0, 0, 0, 226, 115, 118, 151, 99, 74, 206, 192, 54, 119, 86, 106, 49, 37, 96, 59, 221, 128, 153, 67, 247, 21, 68, 152, 230, 248, 87, 123, 211, 20, 82, 78, 227, 103, 150, 3, 228, 241, 212, 135, 191, 10, 56, 71, 251, 59, 3, 198, 205, 78, 200, 215, 69, 84, 146, 233, 213, 137, 19, 41, 160, 58, 140, 13, 30, 194, 71, 229, 158, 175, 223, 193, 113, 148, 103, 64, 107, 123, 10, 192, 132, 32, 99, 155, 134, 142, 192, 45, 84, 54, 154, 67, 187, 51, 121, 9]), DigestItem::Consensus([102, 114, 111, 110], [1, 118, 155, 221, 219, 101, 77, 38, 43, 141, 248, 138, 185, 12, 47, 202, 99, 196, 19, 92, 209, 186, 248, 58, 193, 121, 151, 90, 48, 176, 178, 0, 204, 0]), DigestItem::Other([77, 77, 82, 82, 149, 98, 164, 154, 148, 225, 28, 121, 46, 116, 117, 16, 177, 24, 125, 48, 65, 14, 135, 26, 101, 122, 34, 179, 29, 76, 79, 152, 131, 13, 53, 184]), DigestItem::Seal([66, 65, 66, 69], [120, 87, 160, 229, 237, 120, 176, 110, 92, 74, 145, 18, 131, 116, 251, 84, 175, 192, 134, 112, 101, 232, 38, 33, 59, 123, 21, 82, 185, 193, 203, 127, 205, 241, 31, 221, 55, 60, 200, 174, 73, 194, 204, 76, 14, 3, 206, 208, 141, 208, 199, 222, 17, 9, 75, 40, 189, 49, 32, 161, 255, 0, 100, 130])] } }, authority_list: [(Public(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), 1)], set_id: 0, is_halted: false }
[2021-12-13T07:21:11Z INFO  substrate_relay_helper::headers_initialize] Successfully submitted Pangolin-headers bridge initialization transaction to Pangoro: 0xb0c9949dde6ec3280dddf2dfdbf9ab340ad832740c4890c87a84f3182db8c6f4
[2021-12-13T07:21:20Z DEBUG task_pangolin_pangoro::service::init] source client -> Client { genesis_hash: 0x1a20ef2847058288242829bcd53b0cb228e445e95e195d06758fc23e42625e5d }
[2021-12-13T07:21:20Z DEBUG task_pangolin_pangoro::service::init] target client -> Client { genesis_hash: 0x8e256132e4d6412325b1485dee50c5d2a19a485095b4118b9b555be873c8c7d8 }
[2021-12-13T07:21:24Z INFO  substrate_relay_helper::headers_initialize] Prepared initialization data for Pangoro-headers bridge at Pangolin: InitializationData { header: Header { parent_hash: 0xcc3e6eb42de45fc71f5da8808b24eed4ad2cba93271de33529b8d365d38fa3c8, number: 37, state_root: 0xe89047e162bba0cbe5e0b09993e515f5f0c82cab78d0160d233590d8f3fbfbaa, extrinsics_root: 0xa860dadcd6d80fbdf281b86a6add5d5ae33bdc286533f0ee7d0d5ab64fd144f3, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [2, 0, 0, 0, 0, 187, 40, 73, 16, 0, 0, 0, 0]), DigestItem::Seal([66, 65, 66, 69], [90, 175, 17, 29, 4, 212, 29, 131, 12, 187, 111, 238, 76, 203, 196, 130, 150, 180, 170, 113, 5, 248, 96, 92, 253, 66, 117, 80, 199, 16, 85, 125, 245, 19, 103, 57, 200, 226, 58, 27, 246, 224, 212, 63, 255, 226, 198, 143, 68, 76, 193, 24, 192, 75, 8, 213, 234, 174, 84, 77, 226, 199, 138, 130])] } }, authority_list: [(Public(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), 1)], set_id: 0, is_halted: false }
[2021-12-13T07:21:24Z INFO  substrate_relay_helper::headers_initialize] Successfully submitted Pangoro-headers bridge initialization transaction to Pangolin: 0x3019a37a67adf81be47530a0849b4daf8d22a23f61448b36ee808b758b90ec78
```



```
[2021-12-13T07:23:57Z INFO  messages_relay::message_race_loop] Synced Some(1) of Some(1) nonces in Pangoro::MessagesDelivery -> Pangolin::MessagesDelivery race
[2021-12-13T07:24:02Z INFO  finality_relay::finality_loop] Synced 35 of 48 headers
[2021-12-13T07:24:08Z INFO  finality_relay::finality_loop] Synced 61 of 61 headers

[2021-12-13T07:24:32Z INFO  messages_relay::message_race_loop] Synced Some(1) of Some(1) nonces in Pangoro::MessagesDelivery -> Pangolin::MessagesDelivery race
[2021-12-13T07:24:32Z INFO  messages_relay::message_race_loop] Synced Some(1) of Some(1) nonces in Pangolin::ReceivingConfirmationsDelivery -> Pangoro::ReceivingConfirmationsDelivery race
[2021-12-13T07:24:44Z INFO  finality_relay::finality_loop] Synced 61 of 61 headers
```

**Comment by fewensa** [comment]
Test different `spec_version` and `transaction_version`

pangolin

```
/// This runtime version.
#[sp_version::runtime_version]
pub const VERSION: RuntimeVersion = RuntimeVersion {
	spec_name: sp_runtime::create_runtime_str!("Pangolin"),
	impl_name: sp_runtime::create_runtime_str!("Pangolin"),
	authoring_version: 0,
	spec_version: 2_7_02_0,
	impl_version: 0,
	apis: RUNTIME_API_VERSIONS,
	transaction_version: 0,
};
```

pangoro

```
pub const VERSION: RuntimeVersion = RuntimeVersion {
	spec_name: sp_runtime::create_runtime_str!("Pangoro"),
	impl_name: sp_runtime::create_runtime_str!("Pangoro"),
	authoring_version: 0,
	spec_version: 2_7_03_0,
	impl_version: 0,
	apis: RUNTIME_API_VERSIONS,
	transaction_version: 0,
};
```


bridger
dependent   `pangolin@2_7_01_0`  `pangoro@2_7_01_0`

**Comment by fewensa** [comment]
```
[2021-12-13T07:44:31Z DEBUG task_pangolin_pangoro::service::init] source client -> Client { genesis_hash: 0x2a7623d5c8ccec2e132bc584a1e0361272cd94bc8fc727d4b34a2816be204a2b }
[2021-12-13T07:44:31Z DEBUG task_pangolin_pangoro::service::init] target client -> Client { genesis_hash: 0x2986ad0603cc25caf914bc7b94f23442c1f2a764d3bd0b63337ea6d764a99e7b }
[2021-12-13T07:44:32Z INFO  substrate_relay_helper::headers_initialize] Prepared initialization data for Pangolin-headers bridge at Pangoro: InitializationData { header: Header { parent_hash: 0x7bc2a85bdc55c81eb5263857bf65bce59aad7cf7a8bba09c9878564d47b4e109, number: 34, state_root: 0xd675ae8c8c59f4a08e910f568f4b541ed0ed18a516e15ebfea9dcfb1ab55e709, extrinsics_root: 0x2aff0c6bf5fac8f0474f927a9c3d620f0dce80f86f3a27669166e34292057062, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [2, 0, 0, 0, 0, 163, 41, 73, 16, 0, 0, 0, 0]), DigestItem::Consensus([102, 114, 111, 110], [1, 112, 56, 69, 5, 240, 225, 62, 42, 10, 55, 90, 99, 30, 144, 18, 187, 146, 33, 118, 157, 59, 109, 142, 15, 28, 74, 133, 67, 107, 134, 30, 13, 0]), DigestItem::Other([77, 77, 82, 82, 214, 44, 203, 217, 254, 32, 33, 165, 72, 99, 96, 207, 228, 181, 222, 241, 108, 84, 11, 126, 145, 199, 19, 147, 29, 150, 223, 238, 27, 164, 200, 143]), DigestItem::Seal([66, 65, 66, 69], [100, 16, 30, 140, 19, 153, 208, 128, 105, 110, 12, 60, 19, 107, 183, 84, 55, 148, 99, 255, 166, 170, 237, 253, 55, 206, 144, 39, 123, 120, 56, 57, 13, 217, 116, 187, 104, 139, 135, 137, 196, 120, 95, 67, 230, 32, 198, 33, 162, 165, 6, 145, 159, 71, 199, 25, 98, 197, 45, 55, 112, 193, 220, 129])] } }, authority_list: [(Public(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), 1)], set_id: 0, is_halted: false }
[2021-12-13T07:44:32Z INFO  substrate_relay_helper::headers_initialize] Successfully submitted Pangolin-headers bridge initialization transaction to Pangoro: 0x71b3c5022fc15f1367fe4e9aaef67e027298350e9bf41d6619989856da851396
[2021-12-13T07:44:35Z DEBUG task_pangolin_pangoro::service::init] source client -> Client { genesis_hash: 0x2986ad0603cc25caf914bc7b94f23442c1f2a764d3bd0b63337ea6d764a99e7b }
[2021-12-13T07:44:35Z DEBUG task_pangolin_pangoro::service::init] target client -> Client { genesis_hash: 0x2a7623d5c8ccec2e132bc584a1e0361272cd94bc8fc727d4b34a2816be204a2b }
[2021-12-13T07:44:39Z INFO  substrate_relay_helper::headers_initialize] Prepared initialization data for Pangoro-headers bridge at Pangolin: InitializationData { header: Header { parent_hash: 0xbaa8a438a120be7d4e4e7a01c89db73baf863047f6ee85d9e10722483982feb4, number: 34, state_root: 0xaf2a84480c9450de34c348dcabcb017fd5e31412a52bb4f89e8880b1d511e176, extrinsics_root: 0x7e2c5245319f49745fb52bb39480c5af678432a5b6b064aa05b7376080741906, digest: Digest { logs: [DigestItem::PreRuntime([66, 65, 66, 69], [2, 0, 0, 0, 0, 164, 41, 73, 16, 0, 0, 0, 0]), DigestItem::Seal([66, 65, 66, 69], [116, 118, 142, 8, 229, 174, 50, 215, 250, 108, 255, 144, 1, 13, 187, 36, 78, 7, 17, 118, 9, 96, 112, 10, 88, 240, 151, 135, 72, 131, 88, 81, 159, 66, 66, 180, 213, 98, 130, 208, 244, 34, 94, 160, 28, 251, 123, 236, 181, 129, 247, 42, 210, 76, 221, 217, 237, 96, 215, 221, 154, 160, 7, 140])] } }, authority_list: [(Public(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), 1)], set_id: 0, is_halted: false }
[2021-12-13T07:44:39Z INFO  substrate_relay_helper::headers_initialize] Successfully submitted Pangoro-headers bridge initialization transaction to Pangolin: 0x610e954bd6f3acfcbdb0c3da5a0bd614c480bd7dd6b9c7fb951ff6469ca44db7
```



```
[2021-12-13T07:46:10Z INFO  messages_relay::message_race_loop] Synced Some(0) of Some(1) nonces in Pangoro::MessagesDelivery -> Pangolin::MessagesDelivery race
[2021-12-13T07:46:15Z INFO  finality_relay::finality_loop] Synced 34 of 42 headers
[2021-12-13T07:46:15Z INFO  finality_relay::finality_loop] Synced 48 of 48 headers
[2021-12-13T07:46:16Z TRACE component_pangoro_s2s::feemarket] [pangoro] Determine whether to relay for nonce: 1
[2021-12-13T07:46:16Z INFO  component_pangoro_s2s::feemarket] [pangoro] You are assigned relayer, you must be relay this nonce(1)
[2021-12-13T07:46:16Z INFO  component_pangoro_s2s::feemarket] [pangoro] About nonce 1 decide is true
...
[2021-12-13T07:46:34Z INFO  messages_relay::message_race_loop] Synced Some(1) of Some(1) nonces in Pangoro::MessagesDelivery -> Pangolin::MessagesDelivery race
[2021-12-13T07:46:34Z INFO  messages_relay::message_race_loop] Synced Some(0) of Some(0) nonces in Pangolin::ReceivingConfirmationsDelivery -> Pangoro::ReceivingConfirmationsDelivery race
[2021-12-13T07:46:39Z INFO  finality_relay::finality_loop] Synced 50 of 50 headers
[2021-12-13T07:46:39Z INFO  finality_relay::finality_loop] Synced 34 of 54 headers
```


```
[2021-12-13T07:46:58Z INFO  messages_relay::message_race_loop] Synced Some(1) of Some(1) nonces in Pangolin::ReceivingConfirmationsDelivery -> Pangoro::ReceivingConfirmationsDelivery race
[2021-12-13T07:46:58Z INFO  messages_relay::message_race_loop] Synced Some(1) of Some(1) nonces in Pangoro::MessagesDelivery -> Pangolin::MessagesDelivery race

```



image
image

**Comment by fewensa** [comment]
@AurevoirXavier Please help check my test.

**Comment by fewensa** [comment]
TODO:
1. Merge https://github.com/darwinia-network/parity-bridges-common/pull/11
2. Update and merge https://github.com/darwinia-network/darwinia-common/pull/994
3. Update and merge https://github.com/darwinia-network/darwinia/pull/816
4. Update and merge this pr

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
