### PR TITLE
enhancement microkv

### PR DESCRIPTION
**Pull request by fewensa**
Support namespace and serialize value.

Wait for these pr to be processed 
https://github.com/ex0dus-0x/microkv/pull/10
https://github.com/ex0dus-0x/microkv/pull/11

### CODE REVIEW

**Comment by fewensa** [comment]
https://github.com/fewensa/microkv/pull/1

**Comment by fewensa** [comment]
@HackFisher  ready for review.
this pr only enhances the use of kv. added namespace support, and supports editing data through cli.
 the docs [link](https://github.com/darwinia-network/bridger/blob/61fb63fe40/docs/command.md#kv)

**Comment by HackFisher** [comment]
@fewensa Do we need to any operation before upgrading brider?

**Comment by fewensa** [comment]
Not need, will auto migrate.

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
