### PR TITLE
The next generation bridger

### PR DESCRIPTION
**Pull request by fewensa**
Todo:

- [ ] Wrap kv command and add schema https://github.com/darwinia-network/bridger/issues/343#issuecomment-989568744
- [x] https://github.com/darwinia-network/bridger/issues/316
- [x] https://github.com/darwinia-network/bridger/issues/319
- [ ] https://github.com/darwinia-network/bridger/issues/242
- [ ] #371 

Description: #267 

Includes PR:

- [x] #365
- [x] #370 
- [x] #369 
- [x] #372 
- [x] #373 
- [x] #374
- [x] #378 
- [x] #379 
- [x] #380
- [x] #383
- [x] #384 
- [x] #385
- [x] #388
- [x] #389

### CODE REVIEW

**Comment by fewensa** [comment]
https://github.com/fewensa/bridger/releases/tag/v0.5.0

**Comment by HackFisher** [comment]
```
% ./bridger.sh -h    
+++ readlink -f ./bridger.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
++ dirname
usage: dirname string [...]
+ BIN_PATH=
+ cargo build --manifest-path /frame/Cargo.toml --package darwinia-bridger
error: manifest path `/frame/Cargo.toml` does not exist
+ exit 1
```

**Comment by HackFisher** [comment]
https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Review by HackFisher — APPROVED** [review]
LGTM, good to go after we satisfy the ci/cd and document requests.

**Pull request merged**
