### PR TITLE
Add GitHub Actions to publish the package on crates.io.

### LINKED ISSUE #17: auto ci package release on crates.io
First release and tag,

then ci auto publish on crates.io

### PR DESCRIPTION
**Pull request by wi1dcard**
Closes #17.

### CODE REVIEW

**Comment by HackFisher** [comment]
@wi1dcard is this PR ready for review and merge?

**Comment by wi1dcard** [comment]
All work in this PR has been done. However, I've not tested if it's functioning or not. I'd like to wait for the next release of this repo. That gives me a chance testing and maybe fixing the bugs in the PR before it gets merged. What do you think? @HackFisher

**Comment by HackFisher** [comment]
> All work in this PR has been done. However, I've not tested if it's functioning or not. I'd like to wait for the next release of this repo. That gives me a chance testing and maybe fixing the bugs in the PR before it gets merged. What do you think? @HackFisher

How to test? Just publish a github release, can it be used for testing?

https://github.com/darwinia-network/bridger/releases/tag/v0.0.14

**Comment by wi1dcard** [comment]
> How to test? Just publish a github release, can it be used for testing?
> 
> https://github.com/darwinia-network/bridger/releases/tag/v0.0.14

Sure yes! Thanks for reminding me, havn't noticed that there's already a new version has been released on GitHub. I'll test the CI workflow using that version right now. I'll let you know after this can be merged.

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
